# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  DOCKER_TAG: 'latest'
  DOCKER_GROUP: 'vndg'
  DOCKER_ENV: 'production'

resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: true

steps:
- checkout: self
- script:
    docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
  displayName: 'docker login'
- script: |
    docker pull microsoft/dotnet:2.1.5-aspnetcore-runtime-alpine
    docker pull microsoft/dotnet:2.1.403-sdk-alpine
    docker pull nginx:alpine
    docker pull node:alpine
    docker pull mysql:8.0.12
  displayName: 'Pull Docker Images'
- script: |
    docker build -f ./src/web/Dockerfile -t $(DOCKER_USERNAME)/cs-spa:$(DOCKER_TAG) .
    docker tag $(DOCKER_USERNAME)/cs-spa:$(DOCKER_TAG) $(DOCKER_GROUP)/cs-spa:$(DOCKER_TAG)
    docker push $(DOCKER_GROUP)/cs-spa:$(DOCKER_TAG)
  displayName: 'Build Web - Vuejs'
  
