version: "3.7"

services:
  webapi_gateway:
    image: vndg/webapi-gateway:latest
    restart: always
    build:
      context: .
      dockerfile: src/gateways/webapi-gateway/Dockerfile
    depends_on:
      - product_catalog_api
      # - shopping_cart_api
    networks:
      - coolstore

  product_catalog_api:
    image: vndg/product-catalog-api:latest
    restart: always
    build:
      context: .
      dockerfile: src/microservices/product-catalog-service/VND.CoolStore.ProductCatalog.Grpc/Dockerfile
    depends_on:
      - migration_data
      - sqlserver_data
    networks:
      - coolstore

  # shopping_cart_api:
  #   image: vndg/shopping-cart-api:latest
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: src/microservices/shopping-cart-service/VND.CoolStore.ShoppingCart/Dockerfile
  #   depends_on:
  #     - migration_data
  #     - sqlserver_data
  #   networks:
  #     - coolstore

  access_control_service:
    image: vndg/access-control-service:latest
    restart: always
    build:
      context: .
      dockerfile: src/microservices/access-control-service/VND.CoolStore.AccessControl/Dockerfile
    networks:
      - coolstore

  migration_data:
    image: vndg/migration-data:latest
    build:
      context: .
      dockerfile: ./src/migrations/VND.CoolStore.DbMigration/Dockerfile
    depends_on:
      - sqlserver_data
    networks:
      - coolstore

  sqlserver_data:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    networks:
      - coolstore

networks:
  coolstore:
    name: coolstore-network
