version: "3"

services:

  web:
    environment:
      - PORT=3000
      - REACT_APP_AUTHORITY=http://localhost:5001
      - REACT_APP_API=http://localhost:5000
    ports:
      - 3000:3000

  webapigatewayapp:
    environment:
      - Services__inventoryapp=http://inventoryapp:5002
      - Services__productcatalogapp=http://productcatalogapp:5003
      - Services__shoppingcartapp=http://shoppingcartapp:5004
      - Services__saleapp=http://saleapp:5005
      - OtelZipkin__Endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "5000:5000"

  identityapp:
    ports:
      - "5001:5001"

  inventoryapp:
    environment:
      - ConnectionStrings__postgres=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd;
      - Redis__Url=redis:6379
      - Authn__Authority=http://identityapp:5001
      - Authn__Audience=http://localhost:5001/resources
      - OtelZipkin__Endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "5002:5002"

  productcatalogapp:
    restart: always
    environment:
      - ConnectionStrings__postgres=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd;
      - Redis__Url=redis:6379
      - Authn__Authority=http://identityapp:5001
      - Authn__Audience=http://localhost:5001/resources
      - OtelZipkin__Endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "5003:5003"

  shoppingcartapp:
    environment:
      - ConnectionStrings__postgres=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd;
      - Redis__Url=redis:6379
      - Authn__Authority=http://identityapp:5001
      - Authn__Audience=http://localhost:5001/resources
      - OtelZipkin__Endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "5004:5004"

  saleapp:
    environment:
      - ConnectionStrings__postgres=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd;
      - Redis__Url=redis:6379
      - Authn__Authority=http://identityapp:5001
      - Authn__Audience=http://localhost:5001/resources
      - OtelZipkin__Endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "5005:5005"

  postgresql:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - "5432:5432"

  # elk:
  #   ports:
  #     - "5601:5601"
  #     - "9200:9200"
  #   expose:
  #     - 5601
  #     - 9200

  zipkin:
    ports:
      - "9411:9411"

  redis:
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - "6379:6379"
