version: "3.7"

services:
  webapi_gateway:
    image: vndg/webapi-gateway-v3:latest
    restart: always
    build:
      context: .
      dockerfile: src/gateways/webapi-gateway/Dockerfile
    depends_on:
      - product_catalog_api
      - shopping_cart_api
      - inventory_api
    networks:
      - coolstore

  product_catalog_api:
    image: vndg/product-catalog-api-v3:latest
    restart: always
    build:
      context: .
      dockerfile: src/microservices/product-catalog-service/VND.CoolStore.ProductCatalog.Api/Dockerfile
    depends_on:
      - migration_data
      - sqlserver_data
      - redis
    networks:
      - coolstore

  shopping_cart_api:
    image: vndg/shopping-cart-api-v3:latest
    restart: always
    build:
      context: .
      dockerfile: src/microservices/shopping-cart-service/VND.CoolStore.ShoppingCart.Api/Dockerfile
    depends_on:
      - migration_data
      - sqlserver_data
      - redis
    networks:
      - coolstore

  inventory_api:
    image: vndg/inventory-api-v3:latest
    restart: always
    build:
      context: .
      dockerfile: src/microservices/inventory-service/VND.CoolStore.Inventory.Api/Dockerfile
    depends_on:
      - migration_data
      - sqlserver_data
    networks:
      - coolstore

  access_control_api:
    image: vndg/access-control-api-v3:latest
    restart: always
    build:
      context: .
      dockerfile: src/microservices/access-control-service/VND.CoolStore.AccessControl/Dockerfile
    networks:
      - coolstore

  migration_data:
    image: vndg/migration-data-v3:latest
    build:
      context: .
      dockerfile: ./src/migrations/VND.CoolStore.DbMigration/Dockerfile
    depends_on:
      - sqlserver_data
    networks:
      - coolstore

  redis:
    image: bitnami/redis:5.0.5-debian-9-r124
    restart: always
    networks:
      - coolstore

  sqlserver_data:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    networks:
      - coolstore

networks:
  coolstore:
    name: coolstore-network
