apiVersion: skaffold/v1beta1
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: vndg/cs-mysqldb
    context: .
    docker: {
      dockerfile: ./deploys/dockers/mysqldb/Dockerfile
    }
  - image: vndg/cs-idp-service
    context: .
    docker: {
      dockerfile: ./src/services/idp/Dockerfile
    }
  - image: vndg/cs-cart-service
    context: .
    docker: {
      dockerfile: ./src/services/cart/Dockerfile
    }
  - image: vndg/cs-inventory-service
    context: .
    docker: {
      dockerfile: ./src/services/inventory/Dockerfile
    }
  - image: vndg/cs-review-service
    context: .
    docker: {
      dockerfile: ./src/services/review/Dockerfile
    }
  - image: vndg/cs-catalog-service
    context: .
    docker: {
      dockerfile: ./src/services/catalog/Dockerfile
    }
  - image: vndg/cs-rating-service
    context: .
    docker: {
      dockerfile: ./src/services/rating/Dockerfile
    }
  - image: vndg/cs-spa
    context: .
    docker: {
      dockerfile: ./src/web/Dockerfile
    }

deploy:
  helm: null
  kubectl:
    manifests:
    - ./deploys/k8s/dev-all-in-one.yaml