name: coolstore-on-dapr

extensions:
- name: zipkin
- name: elastic
  logPath: ./.logs

services:

- name: postgres
  image:  postgres
  env:
  - name: POSTGRES_PASSWORD
    value: "P@ssw0rd"
  bindings:
  - port: 5432
    connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};

- name: redis
  image: redis
  bindings:
  - port: 6379
