swagger: '2.0'
info:
  version: '1.0'
  title: API 1.0
  description: 'An application with Swagger, Swashbuckle, and API versioning.'
  termsOfService: Shareware
  contact:
    name: VND
    email: vietnam.devs.group@gmail.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
basePath: /inventory
paths:
  '/api/Availability/{id}':
    get:
      tags:
        - Availability
      operationId: ApiAvailabilityByIdGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uuid
        - name: api-version
          in: query
          description: The requested API version
          required: false
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Inventory'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - oauth2:
            - access_inventory_api
  '/api/Availability':
    get:
      tags:
        - Availability
      operationId: ApiAvailabilityGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: api-version
          in: query
          description: The requested API version
          required: false
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          schema:
            type: string
definitions:
  Inventory:
    type: object
    properties:
      location:
        type: string
      quantity:
        format: int32
        type: integer
      link:
        type: string
      id:
        format: uuid
        type: string
        readOnly: true
      created:
        format: date-time
        type: string
        readOnly: true
      updated:
        format: date-time
        type: string
        readOnly: true
securityDefinitions:
  oauth2:
    flow: implicit
    authorizationUrl: 'http://id.coolstore.local/connect/authorize'
    tokenUrl: 'http://id.coolstore.local/connect/token'
    scopes:
      inventory_api_scope: Inventory APIs
    type: oauth2
tags: []
