gatewaySettings:
  HostSettings__CurrentHostUri: http://localhost:32000/cs
  HostSettings__AuthorityHostUri: http://localhost:32000/idp

idpSettings:
  HostSettings__SwaggerRedirectUri: http://localhost:32000/cs/swagger/oauth2-redirect.html
  HostSettings__SwaggerPostLogoutRedirectUri: http://localhost:32000/cs/swagger
  HostSettings__SwaggerAllowedCorsOrigin: http://localhost:32000
