apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-vs
spec:
  hosts:
  - {{ .Values.hosts.api }}
  gateways:
  - cs-gateway
  http:
  - match:
    - uri:
        prefix: /v1/
    route:
    - destination:
        host: openapi
        port:
          number: 5010
  - match:
    - uri:
        prefix: /catalog/
    route:
    - destination:
        host: catalog
        port:
          number: 5002
  - match:
    - uri:
        prefix: /cart/
    route:
    - destination:
        host: cart
        port:
          number: 5003
  - match:
    - uri:
        prefix: /inventory/
    route:
    - destination:
        host: inventory
        port:
          number: 5004
  - match:
    - uri:
        prefix: /review/
    route:
    - destination:
        host: review
        port:
          number: 5006
  - match:
    - uri:
        prefix: /rating/
    route:
    - destination:
        host: rating
        port:
          number: 5007
---
