apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-vs
spec:
  hosts:
  - {{ .Values.hosts.api }}
  gateways:
  - cs-gateway
  http:
  - match:
    - uri:
        prefix: /v1/
    route:
    - destination:
        host: openapi
        port:
          number: 5010
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: review
        port:
          number: 5006
---
