apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-vs
spec:
  hosts:
  - {{ .Values.hosts.web }}
  gateways:
  - cs-gateway
  http:
  - match:
    - uri:
        prefix: /config/
    - uri:
        prefix: /config
    rewrite:
      uri: /
      authority: {{ .Values.hosts.idp }}
    route:
    - destination:
        host: idp
        port:
          number: 80
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: spa
        port:
          number: 80
---