fullnameOverride: coolstore
image:
  repository: https://github.com/vietnam-devs/coolstore-microservices
  pullPolicy: Always #IfNotPresent
  imageRegistry: vndg
  dockerTag: latest

nginx:
  enabled: false

hosts:
  web: coolstore.local
  api: api.coolstore.local
  idp: id.coolstore.local

gateway:
  ip: 127.0.0.1

idpSettings:
  BasePath: /
  Hosts__Externals__CurrentUri: http://id.coolstore.local/
  SwaggerRedirectUri: http://api.coolstore.local/swagger/oauth2-redirect.html
  SwaggerPostLogoutRedirectUri: http://api.coolstore.local
  SwaggerAllowedCorsOrigin: http://api.coolstore.local

cartSettings:
  Hosts__Externals__CurrentUri: http://api.coolstore.local/cart
  Hosts__Externals__Auth__Uri: http://id.coolstore.local
  Hosts__Externals__Catalog__Uri: http://api.coolstore.local/catalog

inventorySettings:
  Hosts__Externals__CurrentUri: http://api.coolstore.local/inventory
  Hosts__Externals__Auth__Uri: http://id.coolstore.local

reviewSettings:
  Hosts__Externals__CurrentUri: http://api.coolstore.local/review
  Hosts__Externals__Auth__Uri: http://id.coolstore.local
