fullnameOverride: coolstore
image:
  repository: https://github.com/vietnam-devs/coolstore-microservices
  pullPolicy: Always # or IfNotPresent
  imageRegistry: vndg
  dockerTag: latest

nginx:
  enabled: false

hosts:
  web: coolstore.local
  api: api.coolstore.local
  idp: id.coolstore.local

gateway:
  ip: 127.0.0.1

idpSettings:
  BasePath: /
  Hosts__Externals__CurrentUri: http://id.coolstore.local/
  SwaggerRedirectUri: http://api.coolstore.local/swagger/oauth2-redirect.html
  SwaggerPostLogoutRedirectUri: http://api.coolstore.local
  SwaggerAllowedCorsOrigin: http://api.coolstore.local

cartSettings:
  Hosts__Local__Host: 0.0.0.0
  Hosts__Local__Port: 5003
  Hosts__Externals__Catalog__Uri: http://api.coolstore.local/catalog
  Features__EfCore__MySqlDb__FQDN: "cartdb.coolstore:3306"

inventorySettings:
  Hosts__Local__Host: 0.0.0.0
  Hosts__Local__Port: 5004
  Features__EfCore__MySqlDb__FQDN: "inventorydb.coolstore:3306"

reviewSettings:
  Hosts__Local__Host: 0.0.0.0
  Hosts__Local__Port: 5006
  Features__Mongo__ConnString: "mongodb://mongodb:27017"
