apiVersion: v1
kind: Service
metadata:
  name: cart-db-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: cart-db-service
spec:
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  selector:
    app: cart-db
---
