apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: {{ .Release.Namespace }}
  labels:
    app: cart
spec:
  ports:
  - name: grpc
    port: 5003
    targetPort: 5003
    protocol: TCP
  selector:
    app: cart
---
