apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cart-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        transcode: http
        app: cart
        version: v1
    spec:
      containers:
      - name: cart
        image: {{.Values.image.imageRegistry}}/cs-cart-service:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: Hosts__Local__Host
          value: {{ .Values.cartSettings.Host }}
        - name: Hosts__Local__Port
          value: {{ .Values.cartSettings.Port | quote }}
        - name: Hosts__Externals__Catalog__Uri
          value: {{ .Values.cartSettings.CatalogUri }}
        - name: Features__EfCore__MySqlDb__FQDN
          value: {{ .Values.cartSettings.MySqlDbFQDN }}
        - name: Features__EfCore__MySqlDb__Password
          valueFrom:
            secretKeyRef:
              name: cart-secrets
              key: MySqlDbPassword
        ports:
        - containerPort: {{ .Values.cartSettings.Port }}
        readinessProbe:
          initialDelaySeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.cartSettings.Port }}"]
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.cartSettings.Port }}"]
        resources:
          requests:
            cpu: 30m
            memory: 64Mi
          limits:
            cpu: 30m
            memory: 128Mi
---
