apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cart-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cart
        version: v1
    spec:
      containers:
      - name: cart
        image: vndg/cs-cart-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
      # initContainers:
      # - name: init-mydb
      #   image: microsoft/mssql-server-linux:2017-latest
      #   env: 
      #   - name: "ACCEPT_EULA"
      #     value: "Y"
      #   - name: "MSSQL_SA_PASSWORD"
      #     value: "P@ssw0rd"
      #   command: ['sh', '-c', 'echo waiting for mydb; /opt/mssql-tools/bin/sqlcmd -S cart-db-service2 -U cs -P @MSSQL_SA_PASSWORD -l 360 -Q "select getdate()"']
---
