apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        version: v1
    spec:
      containers:
      - name: gateway
        image: vndg/cs-gateway-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "Hosts__BasePath"
          value: {{ .Values.gatewaySettings.Hosts__BasePath }}
        - name: "Hosts__Externals__CurrentUri"
          value: {{ .Values.gatewaySettings.Hosts__Externals__CurrentUri }}
        - name: "Hosts__Externals__Auth__Uri"
          value: {{ .Values.gatewaySettings.Hosts__Externals__Auth__Uri }}
        ports:
        - name: http
          containerPort: 5000
---
