apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        version: v1
    spec:
      containers:
      - name: gateway
        image: vndg/cs-gateway-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "HostSettings__BasePath"
          value: {{ .Values.gatewaySettings.HostSettings__BasePath }}
        - name: "HostSettings__ExternalCurrentHostUri"
          value: {{ .Values.gatewaySettings.HostSettings__ExternalCurrentHostUri }}
        - name: "HostSettings__ExternalAuthHostUri"
          value: {{ .Values.gatewaySettings.HostSettings__ExternalAuthHostUri }}
        ports:
        - name: http
          containerPort: 5000
---
