apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inventory-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory
        version: v1
    spec:
      containers:
      - name: inventory
        image: vndg/cs-inventory-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "Hosts__BasePath"
          value: "/inv/"
        ports:
        - containerPort: 5004
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5004
          initialDelaySeconds: 10
          periodSeconds: 5
---
