apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mymongodb-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mymongodb
        version: v1
    spec:
      containers:
      - name: mymongodb
        image: bitnami/mongodb:latest
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 20m
            memory: 128Mi
---
