{{- if .Values.nginx.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: coolstore-ingress
  namespace: default
spec:
  rules:
  - host: {{ .Values.hosts.web }}
    http:
      paths:
      - path: /
        backend:
          serviceName: spa-service
          servicePort: 8080
  - host: {{ .Values.hosts.idp }}
    http:
      paths:
      - path: /
        backend:
          serviceName: idp-service
          servicePort: 80
  - host: {{ .Values.hosts.api }}
    http:
      paths:
      - path: /
        backend:
          serviceName: gateway-service
          servicePort: 80
{{- end -}}