apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: open-api-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: open-api
        version: v1
    spec:
      containers:
      - name: open-api
        image: {{.Values.image.imageRegistry}}/cs-open-api:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5010
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "100m"
---
