apiVersion: v1
kind: Service
metadata:
  name: open-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: open-api
spec:
  ports:
  - port: 80
    targetPort: 5010
    protocol: TCP
    name: http
  selector:
    app: open-api
---
