apiVersion: v1
kind: Service
metadata:
  name: openapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: openapi
spec:
  ports:
  - port: 5010
    targetPort: 5010
    protocol: TCP
    name: http
  selector:
    app: openapi
---
