apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rating-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        transcode: http
        app: rating
        version: v1
    spec:
      containers:
      - name: rating
        image: {{.Values.image.imageRegistry}}/cs-rating-service:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NODE_ENV
          value: {{ .Values.ratingSettings.NodeEnv }}
        - name: PORT
          value: {{ .Values.ratingSettings.Port }}
        - name: MONGO_DB_URL
          value: {{ .Values.ratingSettings.MongoDbUri }}
        ports:
        - containerPort: {{ .Values.ratingSettings.Port }}
        readinessProbe:
          initialDelaySeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5007"]
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5007"]
        resources:
          requests:
            memory: "400Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "100m"
      initContainers:
      - name: init-mongodb
        image: busybox
        command: ["sh", "-c", "until nc -z mongodb 27017; do Waiting to connect to a database...; sleep 1; done;"]
---
