apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: review-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        transcode: http
        app: review
        version: v1
    spec:
      containers:
      - name: review
        image: {{.Values.image.imageRegistry}}/cs-review-service:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: Hosts__Local__Host
          value: {{ .Values.reviewSettings.Host }}
        - name: Hosts__Local__Port
          value: {{ .Values.reviewSettings.Port | quote}}
        - name: Features__Mongo__ConnString
          value: {{ .Values.reviewSettings.MongoConnString }}
        ports:
        - containerPort: {{ .Values.reviewSettings.Port }}
        readinessProbe:
          initialDelaySeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.reviewSettings.Port }}"]
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.reviewSettings.Port }}"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
