apiVersion: v1
kind: Service
metadata:
  name: review
  namespace: {{ .Release.Namespace }}
  labels:
    app: review
spec:
  ports:
  - name: grpc
    port: {{ .Values.reviewSettings.Port }}
    targetPort: {{ .Values.reviewSettings.Port }}
    protocol: TCP
  selector:
    app: review
---
