apiVersion: v1
kind: Service
metadata:
  name: review
  namespace: {{ .Release.Namespace }}
  labels:
    app: review
spec:
  ports:
  - name: grpc
    port: 5006
    targetPort: 5006
    protocol: TCP
  selector:
    app: review
---
