apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: review-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: review
        version: v1
    spec:
      containers:
      - name: review
        image: {{.Values.image.imageRegistry}}/cs-review-service:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: Hosts__BasePath
          value: /review/
        - name: Hosts__Externals__CurrentUri
          value: {{ .Values.reviewSettings.Hosts__Externals__CurrentUri }}
        - name: Hosts__Externals__Auth__Uri
          value: {{ .Values.reviewSettings.Hosts__Externals__Auth__Uri }}
        - name: Features__EfCore__MySqlDb__FQDN
          value: {{ .Values.reviewSettings.MySqlDb__FQDN }}
        - name: Features__EfCore__MySqlDb__Password
          valueFrom:
            secretKeyRef:
              name: review-secrets
              key: MySqlDbPassword
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "400Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "100m"
---
