apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spa-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spa
        version: v1
    spec:
      containers:
      - name: spa
        image: {{.Values.image.imageRegistry}}/cs-spa:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NODE_ENV
          value: {{ .Values.webSettings.NODE_ENV }}
        - name: NODE_WEB_ENV
          value: {{ .Values.webSettings.NODE_WEB_ENV }}
        - name: NODE_IDP_ENV
          value: {{ .Values.webSettings.NODE_IDP_ENV }}
        - name: NODE_CATALOG_ENV
          value: {{ .Values.webSettings.NODE_CATALOG_ENV }}
        - name: NODE_CART_ENV
          value: {{ .Values.webSettings.NODE_CART_ENV }}
        - name: NODE_INVENTORY_ENV
          value: {{ .Values.webSettings.NODE_INVENTORY_ENV }}
        - name: NODE_RATING_ENV
          value: {{ .Values.webSettings.NODE_RATING_ENV }}
        - name: NODE_IDP_HOST
          value: {{ .Values.webSettings.NODE_IDP_HOST }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "300Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "100m"
---