apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: {{ .Release.Namespace }}
  labels:
    app: webui
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: webui
---
