apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webui-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webui
        version: v1
    spec:
      containers:
      - name: webui
        image: {{.Values.image.imageRegistry}}/cs-webui:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
---