apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-cartdb
  labels:
    app: {{ $.Release.Name }}-cartdb
    chart: {{ template "cart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: {{ $.Release.Name }}-cartdb
    release: {{ .Release.Name }}
---
