apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cart-secret
  labels:
    app: {{ template "cart.name" . }}
    chart: {{ template "cart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  MySqlDbPassword: UEBzc3cwcmQ=