apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  tracing:
    enabled: true
    exporterType: zipkin
    exporterAddress: "http://127.0.0.1:9411/api/v2/spans"
    expandParams: true
    includeBody: true
