# Default values for cart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vndg/cs-cart-service
  tag: latest
  pullPolicy: IfNotPresent

db:
  image:
    repository: vndg/cs-mysqldb
    tag: latest
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  values:
    - name: Hosts__BasePath
      value: /cart/
    - name: Hosts__Externals__CurrentUri
      value: "http://api.coolstore.local/cart"
    - name: Hosts__Externals__Auth__Uri
      value: "http://id.coolstore.local"
    - name: Hosts__Externals__Catalog__Uri
      value: "http://api.coolstore.local/catalog"
    - name: Features__EfCore__MySqlDb__FQDN
      value: "cartdb.coolstore:3306"
  secrets:
    - name: Features__EfCore__MySqlDb__Password
      key: MySqlDbPassword

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
