---
# Source: coolstore/templates/cart-db-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: cart-db-service
  namespace: default
  labels:
    app: cart-db-service
spec:
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  selector:
    app: cart-db
---

---
# Source: coolstore/templates/cart-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: default
  labels:
    app: cart-service
spec:
  ports:
  - port: 80
    targetPort: 5003
    protocol: TCP
    name: http
  selector:
    app: cart
---

---
# Source: coolstore/templates/catalog-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: default
  labels:
    app: catalog-service
spec:
  ports:
  - port: 80
    targetPort: 5002
    protocol: TCP
    name: http
  selector:
    app: catalog
---

---
# Source: coolstore/templates/gateway-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: default
  labels:
    app: gateway-service
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: gateway
---

---
# Source: coolstore/templates/idp-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: idp-service
  namespace: default
  labels:
    app: idp-service
spec:
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: idp
---

---
# Source: coolstore/templates/inventory-db-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: inventory-db-service
  namespace: default
  labels:
    app: inventory-db-service
spec:
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  selector:
    app: inventory-db
---

---
# Source: coolstore/templates/inventory-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: default
  labels:
    app: inventory-service
spec:
  ports:
  - port: 80
    targetPort: 5004
    protocol: TCP
    name: http
  selector:
    app: inventory
---

---
# Source: coolstore/templates/mongodb-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: mongo
  selector:
    app: mongodb
---
---
# Source: coolstore/templates/rating-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: rating-service
  namespace: default
  labels:
    app: rating-service
spec:
  ports:
  - port: 80
    targetPort: 5007
    protocol: TCP
    name: http
  selector:
    app: rating
---

---
# Source: coolstore/templates/cart-db-dep.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cart-db-v1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cart-db
        version: v1
    spec:
      containers:
      - name: cart-db
        image: vndg/cs-mssqldb:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ACCEPT_EULA
          value: Y
        - name: MSSQL_SA_PASSWORD
          value: P@ssw0rd
        ports:
        - containerPort: 1433
---

---
# Source: coolstore/templates/cart-dep.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cart-v1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cart
        version: v1
    spec:
      containers:
      - name: cart
        image: vndg/cs-cart-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: Hosts__BasePath
          value: /cart/
        ports:
        - containerPort: 5003
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5003
          initialDelaySeconds: 10
          periodSeconds: 5
---

---
# Source: coolstore/templates/catalog-dep.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-v1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog
        version: v1
    spec:
      containers:
      - name: catalog
        image: vndg/cs-catalog-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: BASE_PATH
          value: /cat/
        - name: MONGO_DB_URL
          value: mongodb://mongodb:27017/catalog
        ports:
        - containerPort: 5002
---

---
# Source: coolstore/templates/gateway-dep.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-v1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        version: v1
    spec:
      containers:
      - name: gateway
        image: vndg/cs-gateway-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: Hosts__BasePath
          value: /
        - name: Hosts__Externals__CurrentUri
          value: http://api.coolstore.local
        - name: Hosts__Externals__Auth__Uri
          value: http://id.coolstore.local
        ports:
        - name: http
          containerPort: 5000
---

---
# Source: coolstore/templates/idp-dep.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: idp-v1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: idp
        version: v1
    spec:
      containers:
      - name: idp
        image: vndg/cs-idp-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HostSettings__BasePath
          value: /
        - name: HostSettings__SwaggerRedirectUri
          value: http://api.coolstore.local/swagger/oauth2-redirect.html
        - name: HostSettings__SwaggerPostLogoutRedirectUri
          value: http://api.coolstore.local
        - name: HostSettings__SwaggerAllowedCorsOrigin
          value: http://coolstore.local
        ports:
        - name: http
          containerPort: 5001
---

---
# Source: coolstore/templates/inventory-db-dep.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inventory-db-v1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory-db
        version: v1
    spec:
      containers:
      - name: inventory-db
        image: vndg/cs-mssqldb:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ACCEPT_EULA
          value: Y
        - name: MSSQL_SA_PASSWORD
          value: P@ssw0rd
        ports:
        - containerPort: 1433
---

---
# Source: coolstore/templates/inventory-dep.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inventory-v1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory
        version: v1
    spec:
      containers:
      - name: inventory
        image: vndg/cs-inventory-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: Hosts__BasePath
          value: /inv/
        ports:
        - containerPort: 5004
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5004
          initialDelaySeconds: 10
          periodSeconds: 5
---

---
# Source: coolstore/templates/mongodb-dep.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-v1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        version: v1
    spec:
      containers:
      - name: mongodb 
        image: bitnami/mongodb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
---
---
# Source: coolstore/templates/rating-dep.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rating-v1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rating
        version: v1
    spec:
      containers:
      - name: rating
        image: vndg/cs-rating-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: BASE_PATH
          value: /rat/
        - name: MONGO_DB_URL
          value: mongodb://mongodb:27017/rating
        ports:
        - containerPort: 5007
---

---
# Source: coolstore/templates/cs-gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cs-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - coolstore.local
    - api.coolstore.local
    - id.coolstore.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-vs
spec:
  hosts:
  - coolstore.local
  gateways:
  - cs-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: spa-service
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: id-vs
spec:
  hosts:
  - id.coolstore.local
  gateways:
  - cs-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: idp-service
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inv-vs
spec:
  hosts:
  - api.coolstore.local
  gateways:
  - cs-gateway
  http:
  - match:
    - uri:
        prefix: /gw/
    route:
    - destination:
        host: gateway-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /inv/
    route:
    - destination:
        host: inventory-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /cat/
    route:
    - destination:
        host: catalog-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /rat/
    route:
    - destination:
        host: rating-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /cart/
    route:
    - destination:
        host: cart-service
        port:
          number: 80
---
# Source: coolstore/templates/nginx-ingress.yaml

