##################################################################################################
# Inventory service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: inventory
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inventory-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory
        version: v1
    spec:
      containers:
      - name: inventory
        image: vietnamdevsgroup/coolstore-inventory-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "ASPNETCORE_BASEPATH"
          value: "/inventory"
        ports:
        - containerPort: 80
---