apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: coolstore-ingress
  namespace: default
spec:
  backend:
    serviceName: inventory-service
    servicePort: 5000
  rules:
  - http:
      paths:
      - path: /inventory
        backend:
          serviceName: inventory-service
          servicePort: 5000
      - path: /idp
        backend:
          serviceName: idp-service
          servicePort: 5000
      - path: /id
        backend:
          serviceName: idp-service
          servicePort: 5001
