apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: coolstore-ingress
  namespace: default
spec:
  rules:
    - host: coolstore-ingress.kube.local
      http:
        paths:
          - path: /inventory
            backend:
              serviceName: inventory-service
              servicePort: 80