apiVersion: skaffold/v1beta1
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: vndg/cs-cart-service
    context: ./../../
    sync:
      '*.cs': ./src/services/cart/
      '*.json': ./src/services/cart/
    docker: {
      dockerfile: ./src/services/cart/Dockerfile
    }

deploy:
  helm: null
  kubectl:
    manifests:
    - ./../k8s/dev.cart.yaml