apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: spa_mapping
      prefix: /
      service: spa-service:8080
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: gateway_mapping
      prefix: /cs/
      service: gateway-service:5000
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: idp_mapping
      prefix: /idp/
      service: idp-service:5000
spec:
  type: NodePort
  ports:
  - name: ambassador
    port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    service: ambassador
