apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog
        version: v1
    spec:
      containers:
      - name: catalog
        image: vietnamdevsgroup/coolstore-catalog-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
