apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: catalog-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: catalog
---
