apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway-service
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: gateway
---
