apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inventory-db-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory-db
        version: v1
    spec:
      containers:
      - name: inventory-db
        image: microsoft/mssql-server-linux:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
---
