apiVersion: v1
kind: Service
metadata:
  name: spa-service
  labels:
    app: spa-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spa
---
