apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spa-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spa
        version: v1
    spec:
      containers:
      - name: spa
        image: vndg/cs-spa:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
